AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification template describing your function.

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: VisitorCounter
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: VisitorCounterAPI
      StageName: prod
      EndpointConfiguration: REGIONAL

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.lambda_handler
      Runtime: python3.11
      Environment: 
        Variables:
          TABLE_NAME: !Ref DynamoDBTable
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /visitorCount
            Method: get
            RestApiId: !Ref ApiGateway