AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Specification for ckeditor-poc-backend

Parameters:
  Environment:
    Type: String
    AllowedValues:
      - dev
      - prod
    Description: Environment for the stack

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !If [IsProd, VisitorCounterProd, VisitorCounterDev]
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !If [IsProd, VisitorCounterAPIProd, VisitorCounterAPIDev]
      StageName: !If [IsProd, prod, dev]
      EndpointConfiguration: REGIONAL

  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: lambda_handler.lambda_handler
      Runtime: python3.11
      Environment: 
        Variables:
          TABLE_NAME: !If [IsProd, !Ref VisitorCounterProd, !Ref VisitorCounterDev]
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /visitorCount
            Method: get
            RestApiId: !Ref ApiGateway

Conditions:
  IsProd: !Equals [ !Ref Environment, "prod" ]
